### ISSUE TITLE
Barfs on escaped quotes within strings

### ISSUE THREAD

**Issue by wuffo** [mmghv/sublime-monokai-rich#4]
Like this, in PHP: 
`$string = '\'';`

**Comment by mmghv** [comment]
If you mean the different coloring for the escaped string and the backslash, This is the intended behavior and it's taken from the original scheme without changing.

![echo](https://cloud.githubusercontent.com/assets/5418859/21104458/3a805d28-c08f-11e6-9061-8bddfd8161de.PNG)
